### ISSUE TITLE
When running vim-go and vim-gingo filetype gets set to ginkgo

### ISSUE THREAD

**Issue by bonzofenix** [ivy/vim-ginkgo#4]
It seems like I have to manually set the filetype to `ginkgo` through the command `setfiletype` in vim.

 Is there any way to set the priority for filetype detection?

Thanks!

**Comment by ivy** [comment]
@bonzofenix Sorry, I wouldn't know off the top of my head how to fix that. I don't have that experience with [fatih/vim-go](https://github.com/fatih/vim-go) and `Plug 'vim-ginkgo'` added _after_ in my bundle.

In the worst case, you could try adding this line to your `.vimrc`:

https://github.com/ivy/vim-ginkgo/blob/f9bc33f47f449c5e080fb72e3818de36ef9bb6ef/ftdetect/ginkgo.vim#L2
